vim.keymap.set("n", "]b", ":BufferLineCycleNext<CR>")
vim.keymap.set("n", "[b", ":BufferLineCyclePrev<CR>")
vim.keymap.set("n", "<leader>bp", ":BufferLinePick<CR>")
vim.keymap.set("n", "<leader>bx", ":BufferLinePickClose<CR>")
vim.keymap.set("n", "<leader>bdo", ":BufferLineCloseOthers<CR>")
vim.keymap.set("n", "<leader>bdl", ":BufferLineCloseLeft<CR>")
vim.keymap.set("n", "<leader>bdr", ":BufferLineCloseRight<CR>")
